version: '2'
services:
  tmetric:
    image: webdevops/php-nginx-dev:8.0
    environment:
      - PHP_DISPLAY_ERRORS=1
      - XDEBUG_MODE=develop,debug
    ports:
      - 8080:80
    volumes:
      - .:/app
