version: '2'
services:
  tmetric:
    image: webdevops/php-nginx-dev:8.0
    ports:
      - 8080:80
    volumes:
      - .:/app

  redis:
    image: redis:3.2
    volumes:
      - tmetric-redis:/data

volumes:
  tmetric-redis:
    driver: local
